name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Install Qt
      uses: jurplel/install-qt-action@v2.1.0
      with:
        version: 5.12.6
        target: android
        arch: android_armv7 

    - name: 1UP
      run: |
        cd ..
        echo "---"
        ls -al ./Qt/5.12.6/android_armv7/

#        echo "---"
#        ls -al
#        echo "---"
#        ls -al ./Qt
#        echo "---"
#        ls -al ./Qt/5.12.6
        
#    - name: Install Firebase C++ SDK
#      run: |
#        curl -L https://firebase.google.com/download/cpp -o firebase_cpp_sdk.zip
#        unzip firebase_cpp_sdk.zip

    #- name: Install QtFirebase
    #  run: |
    #    git clone https://github.com/Larpon/QtFirebase.git

#    - name: Install QtFirebaseExample
 #     run: |
  #      git clone https://github.com/Larpon/QtFirebaseExample.git

   # - name: Setup
    #  run: |
     #   ls -al
      #  ln -s firebase_cpp_sdk QtFirebase/firebase_cpp_sdk
       # ln -s QtFirebase QtFirebaseExample/extensions/QtFirebase

#    - name: Run QMake
 #     run: |
  #      cd "QtFirebaseExample/"
   #     mkdir build && cd build
    #    ${Qt5_Dir}/Qt/5.12.6/android_armv7/bin/qmake ../
        
#    - name: Run Make
 #     run: |
  #      make
