name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Install Qt
      uses: jurplel/install-qt-action@v2.1.0
      with:
        version: 5.12.6
        target: android
        arch: android_armv7 

#    - name: 1UP
#      run: |
#        cd ..
#        export WORK="$(readlink -f "${RUNNER_WORKSPACE}/..")"
#        echo "---"
#        echo "Work dir: ${WORK}"
#        echo "---"
#        ls -al ./Qt/5.12.6/android_armv7/bin
#        echo "---"
#        echo "$(readlink -f ./Qt)"
#        echo "---"
#        echo "$(readlink -f "${Qt5_Dir}")"

#        echo "---"
#        ls -al
#        echo "---"
#        ls -al ./Qt
#        echo "---"
#        ls -al ./Qt/5.12.6
        
    - name: Install Firebase C++ SDK
      run: |
        cd ..
        curl -L https://firebase.google.com/download/cpp -o firebase_cpp_sdk.zip
        unzip firebase_cpp_sdk.zip

    #- name: Install QtFirebase
    #  run: |
    #    git clone https://github.com/Larpon/QtFirebase.git

    - name: Install QtFirebaseExample
      run: |
        cd ..
        git clone https://github.com/Larpon/QtFirebaseExample.git

    - name: Setup
      run: |
        cd ..
        ls -al
        echo "---"
        ls -al ..
        echo "---"
        export WORK="$(readlink -f "${RUNNER_WORKSPACE}/..")"
        
        ln -s ${WORK}/firebase_cpp_sdk ${WORK}/QtFirebase/firebase_cpp_sdk
        ln -s ${WORK}/QtFirebase ${WORK}/QtFirebaseExample/extensions/QtFirebase

    - name: Run QMake
      run: |
        cd ..
        cd "QtFirebaseExample/"
        mkdir build && cd build
        ${Qt5_Dir}/bin/qmake ../
        
    - name: Run Make
      run: |
        make
