name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        
    - name: Install Qt
      uses: jurplel/install-qt-action@v2.1.0
      with:
        version: 5.12.6
        target: android
        dir: /qt/

    - name: Install Firebase C++ SDK
      run: |
        curl -L https://firebase.google.com/download/cpp -o firebase_cpp_sdk.zip
        unzip firebase_cpp_sdk.zip

    - name: Install QtFirebase
      run: |
        git clone https://github.com/Larpon/QtFirebase.git qtfb

    - name: Install QtFirebaseExample
      run: |
        git clone https://github.com/Larpon/QtFirebaseExample.git qtfbex

    - name: Setup
      run: |
        ln -s "$(readlink -f firebase_cpp_sdk)" "$(readlink -f qtfb)"/firebase_cpp_sdk
        ln -s "$(readlink -f QtFirebase) "$(readlink -f qtfbex)"/extensions/QtFirebase

    - name: Run QMake
      run: |
        cd qtfbex
        ${Qt5_Dir}/Qt/5.12.6/android_armv7/bin/qmake
        
    - name: Run Make
      run: |
        cd qtfbex
        make
