name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    
    - name: Setup ENV
      run: |
        export WORK="$(readlink -f "${RUNNER_WORKSPACE}")"
        
    - name: Install Qt
      uses: jurplel/install-qt-action@v2.1.0
      with:
        version: 5.12.6
        target: android
        arch: android_armv7 

    - name: Install Firebase C++ SDK
      run: |
        curl -L https://firebase.google.com/download/cpp -o firebase_cpp_sdk.zip
        unzip firebase_cpp_sdk.zip

    #- name: Install QtFirebase
    #  run: |
    #    git clone https://github.com/Larpon/QtFirebase.git

    - name: Install QtFirebaseExample
      run: |
        git clone https://github.com/Larpon/QtFirebaseExample.git

    - name: Setup
      run: |
        ln -s "${WORK}/firebase_cpp_sdk" "${WORK}/QtFirebase/firebase_cpp_sdk"
        ln -s "${WORK}/QtFirebase" "${WORK}/QtFirebaseExample/extensions/QtFirebase"

    - name: Run QMake
      run: |
        cd "${WORK}/QtFirebaseExample/"
        mkdir build && cd build
        ${Qt5_Dir}/Qt/5.12.6/android_armv7/bin/qmake ../
        
    - name: Run Make
      run: |
        cd "${WORK}/QtFirebaseExample/build"
        make
